// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package xxxxxyyy

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// XxxxxyyyClient is the client API for Xxxxxyyy service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type XxxxxyyyClient interface {
	SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
}

type xxxxxyyyClient struct {
	cc grpc.ClientConnInterface
}

func NewXxxxxyyyClient(cc grpc.ClientConnInterface) XxxxxyyyClient {
	return &xxxxxyyyClient{cc}
}

func (c *xxxxxyyyClient) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	out := new(HelloReply)
	err := c.cc.Invoke(ctx, "/xxxx.xxxxxyyy.xxxxxyyy/SayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// XxxxxyyyServer is the server API for Xxxxxyyy service.
// All implementations must embed UnimplementedXxxxxyyyServer
// for forward compatibility
type XxxxxyyyServer interface {
	SayHello(context.Context, *HelloRequest) (*HelloReply, error)
	mustEmbedUnimplementedXxxxxyyyServer()
}

// UnimplementedXxxxxyyyServer must be embedded to have forward compatible implementations.
type UnimplementedXxxxxyyyServer struct {
}

func (UnimplementedXxxxxyyyServer) SayHello(context.Context, *HelloRequest) (*HelloReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}
func (UnimplementedXxxxxyyyServer) mustEmbedUnimplementedXxxxxyyyServer() {}

// UnsafeXxxxxyyyServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to XxxxxyyyServer will
// result in compilation errors.
type UnsafeXxxxxyyyServer interface {
	mustEmbedUnimplementedXxxxxyyyServer()
}

func RegisterXxxxxyyyServer(s grpc.ServiceRegistrar, srv XxxxxyyyServer) {
	s.RegisterService(&Xxxxxyyy_ServiceDesc, srv)
}

func _Xxxxxyyy_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(XxxxxyyyServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/xxxx.xxxxxyyy.xxxxxyyy/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(XxxxxyyyServer).SayHello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Xxxxxyyy_ServiceDesc is the grpc.ServiceDesc for Xxxxxyyy service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Xxxxxyyy_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "xxxx.xxxxxyyy.xxxxxyyy",
	HandlerType: (*XxxxxyyyServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _Xxxxxyyy_SayHello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "xxxxxyyy.proto",
}
