// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package masonxxxxa

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// TmasonxxxxClient is the client API for Tmasonxxxx service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TmasonxxxxClient interface {
	SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
}

type tmasonxxxxClient struct {
	cc grpc.ClientConnInterface
}

func NewTmasonxxxxClient(cc grpc.ClientConnInterface) TmasonxxxxClient {
	return &tmasonxxxxClient{cc}
}

func (c *tmasonxxxxClient) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	out := new(HelloReply)
	err := c.cc.Invoke(ctx, "/masonxxxa.masonxxxxa.Tmasonxxxx/SayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TmasonxxxxServer is the server API for Tmasonxxxx service.
// All implementations must embed UnimplementedTmasonxxxxServer
// for forward compatibility
type TmasonxxxxServer interface {
	SayHello(context.Context, *HelloRequest) (*HelloReply, error)
	mustEmbedUnimplementedTmasonxxxxServer()
}

// UnimplementedTmasonxxxxServer must be embedded to have forward compatible implementations.
type UnimplementedTmasonxxxxServer struct {
}

func (UnimplementedTmasonxxxxServer) SayHello(context.Context, *HelloRequest) (*HelloReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}
func (UnimplementedTmasonxxxxServer) mustEmbedUnimplementedTmasonxxxxServer() {}

// UnsafeTmasonxxxxServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TmasonxxxxServer will
// result in compilation errors.
type UnsafeTmasonxxxxServer interface {
	mustEmbedUnimplementedTmasonxxxxServer()
}

func RegisterTmasonxxxxServer(s grpc.ServiceRegistrar, srv TmasonxxxxServer) {
	s.RegisterService(&Tmasonxxxx_ServiceDesc, srv)
}

func _Tmasonxxxx_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TmasonxxxxServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/masonxxxa.masonxxxxa.Tmasonxxxx/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TmasonxxxxServer).SayHello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Tmasonxxxx_ServiceDesc is the grpc.ServiceDesc for Tmasonxxxx service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Tmasonxxxx_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "masonxxxa.masonxxxxa.Tmasonxxxx",
	HandlerType: (*TmasonxxxxServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _Tmasonxxxx_SayHello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "Tmasonxxxx.proto",
}
