// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package XXXX

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AXXXClient is the client API for AXXX service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AXXXClient interface {
	SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
}

type aXXXClient struct {
	cc grpc.ClientConnInterface
}

func NewAXXXClient(cc grpc.ClientConnInterface) AXXXClient {
	return &aXXXClient{cc}
}

func (c *aXXXClient) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	out := new(HelloReply)
	err := c.cc.Invoke(ctx, "/XX.XXXX.AXXX/SayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AXXXServer is the server API for AXXX service.
// All implementations must embed UnimplementedAXXXServer
// for forward compatibility
type AXXXServer interface {
	SayHello(context.Context, *HelloRequest) (*HelloReply, error)
	mustEmbedUnimplementedAXXXServer()
}

// UnimplementedAXXXServer must be embedded to have forward compatible implementations.
type UnimplementedAXXXServer struct {
}

func (UnimplementedAXXXServer) SayHello(context.Context, *HelloRequest) (*HelloReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}
func (UnimplementedAXXXServer) mustEmbedUnimplementedAXXXServer() {}

// UnsafeAXXXServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AXXXServer will
// result in compilation errors.
type UnsafeAXXXServer interface {
	mustEmbedUnimplementedAXXXServer()
}

func RegisterAXXXServer(s grpc.ServiceRegistrar, srv AXXXServer) {
	s.RegisterService(&AXXX_ServiceDesc, srv)
}

func _AXXX_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AXXXServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/XX.XXXX.AXXX/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AXXXServer).SayHello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AXXX_ServiceDesc is the grpc.ServiceDesc for AXXX service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AXXX_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "XX.XXXX.AXXX",
	HandlerType: (*AXXXServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _AXXX_SayHello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "AXXX.proto",
}
