// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package masonxxx

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// TmasonClient is the client API for Tmason service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TmasonClient interface {
	SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
}

type tmasonClient struct {
	cc grpc.ClientConnInterface
}

func NewTmasonClient(cc grpc.ClientConnInterface) TmasonClient {
	return &tmasonClient{cc}
}

func (c *tmasonClient) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	out := new(HelloReply)
	err := c.cc.Invoke(ctx, "/masonxxx.masonxxx.Tmason/SayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TmasonServer is the server API for Tmason service.
// All implementations must embed UnimplementedTmasonServer
// for forward compatibility
type TmasonServer interface {
	SayHello(context.Context, *HelloRequest) (*HelloReply, error)
	mustEmbedUnimplementedTmasonServer()
}

// UnimplementedTmasonServer must be embedded to have forward compatible implementations.
type UnimplementedTmasonServer struct {
}

func (UnimplementedTmasonServer) SayHello(context.Context, *HelloRequest) (*HelloReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}
func (UnimplementedTmasonServer) mustEmbedUnimplementedTmasonServer() {}

// UnsafeTmasonServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TmasonServer will
// result in compilation errors.
type UnsafeTmasonServer interface {
	mustEmbedUnimplementedTmasonServer()
}

func RegisterTmasonServer(s grpc.ServiceRegistrar, srv TmasonServer) {
	s.RegisterService(&Tmason_ServiceDesc, srv)
}

func _Tmason_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TmasonServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/masonxxx.masonxxx.Tmason/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TmasonServer).SayHello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Tmason_ServiceDesc is the grpc.ServiceDesc for Tmason service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Tmason_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "masonxxx.masonxxx.Tmason",
	HandlerType: (*TmasonServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _Tmason_SayHello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "Tmason.proto",
}
